version: 0.2


env:
  shell: bash

phases:

  install:
    runtime-versions:
      python: 3.8

  build:
    commands:
      - echo Build started on `date`
      - aws --version
      - uname -a 
      - cat /etc/*release

